server:
  port: 8858
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.61.41:3306/trantal_sys
    username: admin
    password: 123456
  data:
    mongodb:
      database: Trantal_logs
      host: 49.232.61.41
      port: 27017
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
#        server-addr: 49.232.61.41:8848/nacos/
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
#        server-addr: 49.232.61.41:8848/nacos/
        server-addr: localhost:8848
        username: nacos
        password: nacos
    loadbalancer:
      ribbon:
        enabled: false
  boot:
    admin:
      client:
        url: 49.232.61.41:9001
logging:
  config:
    classpath: logback-spring.xml
Mybatis:
  mapper-locations: Mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
ribbon:
  nacos:
    enabled: true

