spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.61.41:3306/trantal
    username: root
    password:
  data:
    mongodb:
      host: 49.232.61.41
#      host: localhost
      port: 27017
      database: Trantal_logs
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      config:
        server-addr: 49.232.61.41:8848/nacos/
  boot:
    admin:
      client:
        url: localhost:9001
logging:
  config:
    classpath: logback-spring.xml
Mybatis:
  mapper-locations: Mapper/*.xml
server:
  port: 8858
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
ribbon:
  nacos:
    enabled: true

