server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 49.232.61.41:8848
#        namespace: public
  #        server-addr: localhost:8848/nacos
#        username: nacos
#        password: nacos
  boot:
    admin:
      server:
        url: localhost:9001
      client:
        url: localhost:9001
      discovery:
        enabled: true
        discovery-services: nacos # 使用的注册中心类型
  application:
    name: admin
management:
  endpoints:
    web:
      exposure:
        include: health


