spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trantal_sys
    username: root
    password: 20001120
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
logging:
  config:
    classpath: logback-spring.xml
Mybatis:
  mapper-locations: Mapper/*.xml


