server:
  port: 80
spring:
  application:
    name: system-gateway

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  boot:
    admin:
      client:
        url: localhost:9001
  cloud:
    gateway:
      routes:
        #用户模块动态路由设置
        - id: system-user
          uri: lb://system-user/
#          uri: http://localhost:8888/
          predicates:
            - Path=/User/**, /Receive/**, /v3/api-docs/user
        #订单模块动态路由设置
        - id: system-order
          uri: lb://system-order/
#          uri: http://localhost:8868/
          predicates:
            - Path=/Order/**, /v3/api-docs/order
        #商品模块动态路由设置
        - id: system-object
          uri: lb://system-object/
          predicates:
            - Path=/Object/**, /v3/api-docs/object
        #购物车模块动态路由设置
        - id: system-shop
          uri: lb://system-shop/
          predicates:
            - Path=/Shop/**, /v3/api-docs/shop
        #商品分类模块动态路由设置
        - id: system-objclasses
          uri: lb://system-objclasses/
          predicates:
            - Path=/ObjClasses/**, /v3/api-docs/objclasses
#        #订单模块动态路由设置
#        - id: system-order
#          uri: lb://system-order/
#          predicates:
#            - Path=/Order/**, /v3/api-docs/order

      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: localhost:8848/nacos/
        enabled: true
  logging:
    level:
      org:
        springframework:
          cloud.gateway: DEBUG
          http.server.reactive: DEBUG
          web.reactive: DEBUG