server:
  port: 8818
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.61.41:3306/trantal_sys
    username: admin
    password: 123456
  data:
    mongodb:
      database: Trantal_logs
      host: 49.232.61.41
      port: 27017
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
    livereload:
      enabled: true
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      config:
        server-addr: 49.232.61.41:8848
        username: nacos
        password: nacos
#        server-addr: localhost:8848
      discovery:
        server-addr: 49.232.61.41:8848
  #        server-addr: localhost:8848
        username: nacos
        password: nacos
  boot:
    admin:
      client:
        url: localhost:9001
logging:
  config:
    classpath: logback-spring.xml
Mybatis:
  mapper-locations: Mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#system-object:
#  ribbon:
#    listOfServers: 192.168.11.98:8898  # Nacos 注册中心的地址和端口


